### ISSUE TITLE
Erro no cabeçalho de requisição sua estrutura mudou

### ISSUE THREAD

**Issue by faelp22** [jansenfelipe/cpf-gratis#10]
Problema no sistema de validação de CPF da Receita Federal, agora na lista de dados do cabeçalho de resposta: 
`$headers = $client->getResponse()->getHeaders();` 

na chave: 'Set-Cookie':
`$cookie = $headers['Set-Cookie'][0];` da `class CpfGratis` linhas 28 e 29.

Não existe mais essa chave, sendo assim o sistema fica impossibilitado de validar o captcha sem o valor do cookie. Porem depois de uma analise notei que o cookie continua existindo mas em outra chave: 'Cookie' [PrintCPF](https://drive.google.com/open?id=0BzhTQpag0eUBVDJ3M2hvMHN1ems), já na versão de validação de CNPJ a estrutura continua normal: [PrintCNPJ](https://drive.google.com/open?id=0BzhTQpag0eUBSnZzUmNZNTFrQms).

Como posso ser útil para ajudar a resolver esse problema?

**Comment by jansenfelipe** [comment]
Olá @faelp22 ! Para ajudar, basta enviar um PR com a correção no código :)

**Comment by kcirtapsi** [comment]
Olá @faelp22  e @jansenfelipe, conseguiram a correção para este problema? 

Desde ontem estou com esse problema também, percebi que no navegador, ao limpar o cache e em seguida recarregar a página o cookie é exibido no header de resposta, porém nas demais requisições o cookie não é exibido.

Obrigado.

**Comment by faelp22** [comment]
Ainda não, estou vendo aqui como recuperar o Cookie pois o mesmo não esta mais a resposta do [header](https://drive.google.com/file/d/0BzhTQpag0eUBSU1zSnp2Y0VwXzg/view?usp=sharing), mas está no [objeto internalRequest e request do Symfony\Component\BrowserKit\Request](https://drive.google.com/file/d/0BzhTQpag0eUBVmZsb2pzN1EzVUU/view?usp=sharing).

**Comment by kcirtapsi** [comment]
@faelp22 @jansenfelipe  uma pessoa deu uma força nesse ponto da recuperação do cookie, porém de outra forma, veja:

[http://stackoverflow.com/questions/41682325/php-curl-get-cookie-from-remote-webpage](url)

Consegui recuperar o cookie, mas mesmo assim a consulta não funciona na hora de validar o captcha, aí não sei dizer se esse cookie recuperado é o correto ou se teve alguma outra alteração no site da receita que está impedindo.

Espero que ajude.

**Comment by faelp22** [comment]
@kcirtapsi consegui resolver também estou fazendo testes, acho que você não colocou link da sua solução.

**Comment by kcirtapsi** [comment]
[http://stackoverflow.com/questions/41682325/php-curl-get-cookie-from-remote-webpage](url)  Tente ver agora @faelp22

**Comment by faelp22** [comment]
@kcirtapsi está dando 404 no seu link

**Comment by kcirtapsi** [comment]
@faelp22 , deve ser alguma coisa que fiz errado na hora de colocar o link, removi o http, vou enviar como texto mesmo:

stackoverflow.com/questions/41682325/php-curl-get-cookie-from-remote-webpage

**Comment by faelp22** [comment]
Consegui pegar o cookie e [enviar](https://drive.google.com/file/d/0BzhTQpag0eUBTlQybFVqNHlxbEE/view?usp=sharing) para o site da receita mas ainda continuo recebendo o error: "The current node list is empty." @jansenfelipe você tem alguma ideia?

**Comment by faelp22** [comment]
@jansenfelipe @kcirtapsi acho que eles mudaram a estrutura do [html](https://drive.google.com/file/d/0BzhTQpag0eUBSFdQMHFrbDlXSmc/view?usp=sharing) também.

**Comment by kcirtapsi** [comment]
Conseguiu realizar o ajuste e consultar @faelp22  ?

**Comment by faelp22** [comment]
@kcirtapsi consegui recuperar o cookie, agora tem outro problema.

**Comment by faelp22** [comment]
Pronto resolvido, a segunda mudança que houve foi que a url de destino também foi mudada.

**Comment by kcirtapsi** [comment]
opa, como faço pra utilizar essas alterações @faelp22 ? Tenho como ir na página principal do projeto e fazer download?

**Comment by faelp22** [comment]
#12 pronto foi enviado atualização.

**Comment by faelp22** [comment]
@kcirtapsi assim que o @jansenfelipe aceitar a atualização é só fazer um composer update

**Comment by kcirtapsi** [comment]
Haa blz... muito obrigado @faelp22  e @jansenfelipe, estou ansioso pra voltar a usar rs.

**Comment by jansenfelipe** [comment]
@faelp22 @kcirtapsi  Valeu demais! Chegando em casa vou testar aqui e gerar a versão com correção!
