### ISSUE TITLE
Não instala pelo Composer

### ISSUE THREAD

**Issue by wwebdevelop** [jansenfelipe/cpf-gratis#5]
Não instala pelo composer. Segue a mensagem
![falha](https://cloud.githubusercontent.com/assets/11801892/10974522/5f233ed6-83c1-11e5-913c-0ddbb0e4d902.png)

**Comment by wwebdevelop** [comment]
Eu baixei o Goutte, porém o cpfGratis pede uma versão específica dessa extensão.

Então ele não instala

**Comment by jansenfelipe** [comment]
Olá @wwebdevelop ! Realmente.. Precisa da versão 2.0 do https://packagist.org/packages/fabpot/goutte 

Por isso deu problema... =/
